#!/bin/sh

# script/audit: runs gosec against the mod file to find security issues
#                   

# Run everything except for rule G107
# this is due to G107 requiring non dynamic URLs for get
# since we are implicitely trusting sendsafely here we have
# very little choice but to ignore this rule
# see https://securego.io/docs/rules/g107.html
 gosec -exclude=G107 ./...