#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

mkdir -p ./cmd/local/jvmcollect/lib/
curl -L -o ./cmd/local/jvmcollect/lib/sjk.jar https://github.com/rsvihladremio/jvm-tools/releases/download/0.22-SNAPSHOT/sjk-0.22-SNAPSHOT.jar

echo "Checking if license-header-checker is installed"
date "+%H:%M:%S"

if ! type "license-header-checker" > /dev/null; then
  echo "license-header-checker not found installing.."
  date "+%H:%M:%S"
  go install github.com/lluissm/license-header-checker/cmd/license-header-checker@latest
fi

echo "Checking if golangci-lint is installed…"
date "+%H:%M:%S"

if ! type "golangci-lint" > /dev/null; then
    echo "golaningci-lint not found installing…"
    date "+%H:%M:%S"

    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
fi

echo "Checking if gosec is installed…"
date "+%H:%M:%S"

if ! type "gosec" > /dev/null; then
    echo "gosec not found installing…"
    date "+%H:%M:%S"
    go install github.com/securego/gosec/v2/cmd/gosec@v2.16.0
fi

