#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

echo "Checking if license-header-checker is installed"
date "+%H:%M:%S"

if ! type "license-header-checker" > /dev/null; then
  echo "license-header-checker not found installing.."
  date "+%H:%M:%S"
  curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash
fi

echo "Checking if golangci-lint is installed…"
date "+%H:%M:%S"

if ! type "golangci-lint" > /dev/null; then
    echo "golaningci-lint not found installing…"
    date "+%H:%M:%S"

    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2
fi

echo "Checking if gosec is installed…"
date "+%H:%M:%S"

if ! type "gosec" > /dev/null; then
    echo "gosec not found installing…"
    date "+%H:%M:%S"
    curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.16.0
fi

