#!/bin/sh

# script/build-grav: build binary for graviton servers to be run from the same servers

echo "Checking if zip is installed…"
date "+%H:%M:%S"

if ! type "zip" > /dev/null; then
    echo "zip not found installing…"
    date "+%H:%M:%S"
    OS="`uname`"
    case $OS in
      'Linux')
        if type "apt" > /dev/null; then
            echo "detected debian based system installing via apt"
            sudo apt install zip
        fi
        if type "yum" > /dev/null; then
            echo "detected rpm based system installing via yum"
            sudo yum install zip
        fi
        ;;
      'WindowsNT')
        echo "install gnu zip and try again http://gnuwin32.sourceforge.net/packages/zip.htm"
        exit 1
        ;;
      'Darwin') 
        if type "brew" > /dev/null; then
            brew install zip
        else
            echo "install homebrew to have zip https://brew.sh/"
            exit 1
        fi
        ;;
      *) ;;
      esac
fi
# this is also set in script/build and is a copy paste
GIT_SHA=`git rev-parse --short HEAD`
VERSION=$1
LDFLAGS="-X github.com/dremio/dremio-diagnostic-collector/v3/pkg/versions.GitSha=$GIT_SHA -X github.com/dremio/dremio-diagnostic-collector/v3/pkg/versions.Version=$VERSION"

echo "Cleaning bin folder…"
date "+%H:%M:%S"
./script/clean

echo "Building embedded binary for linux-arm64"
date "+%H:%M:%S"
touch ./cmd/root/ddcbinary/output/ddc.zip
GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o ./bin/ddc
cp ./default-ddc.yaml ./bin/ddc.yaml
zip ./bin/ddc.zip ./bin/ddc
rm ./bin/ddc
mv ./bin/ddc.zip ./cmd/root/ddcbinary/output/ddc.zip
echo "Building linux-arm64"
date "+%H:%M:%S"
GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o ./bin/ddc
zip ./bin/ddc-linux-arm64-arm64.zip ./bin/ddc ./bin/ddc.yaml ./README.md ./FAQ.md