#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

echo "Validating if all dependencies are fullfilled…"
date "+%H:%M:%S"
./script/bootstrap

echo "Tests started at…"
date "+%H:%M:%S"

./script/test


echo "Linting started at…"
date "+%H:%M:%S"

./script/lint

echo "Audit started at…"
date "+%H:%M:%S"

./script/audit