#!/bin/sh

# script/cover: Run the coverage

#set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "appending coverage results to test.out"
go tool cover -func=covprofile >> test.out
cat test.out
