#!/bin/sh

# script/install: Script to install from source, eventually when there 
#                 are releases this will switch to latest release

curl -L -o bootstrap https://raw.githubusercontent.com/rsvihladremio/dremio-diagnostic-collector/main/script/bootstrap
sh ./bootstrap
curl -L -o main.zip https://github.com/rsvihladremio/dremio-diagnostic-collector/archive/refs/heads/main.zip
unzip main.zip
cd dremio-diagnostic-collector 
./script/build
sudo cp ./bin/ddc /usr/local/bin
cd ..
rm -fr dremio-diagnostic-collector-main 
rm boostrap