#!/bin/sh

# script/install: Script to install from source, eventually when there 
#                 are releases this will switch to latest release


DOWNLOAD=""
OS=""
ARCH=`uname -m`
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	OS="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
	OS="darwin"
elif [[ "$OSTYPE" == "cygwin" ]]; then
	OS="linux"
elif [[ "$OSTYPE" == "msys" ]]; then
	OS="linux"
else
        echo script for os type $OSTYPE is unsupported, build from sournce instead 
	exit 1
fi

DOWNLOAD=ddc-$OS-$ARCH.zip
curl -o $DOWNLOAD -L "https://github.com/rsvihladremio/dremio-diagnostic-collector/releases/latest/download/$DOWNLOAD"
unzip $DOWNLOAD
sudo mv ./bin/ddc /usr/local/bin/
rm $DOWNLOAD
rm -fr ddc-$OS-$ARCH
