#!/bin/sh

# script/test: Run all tests

#set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

./script/clean
./script/build

 go test -timeout 20m -race -coverpkg=./... -coverprofile=covprofile ./...
