#!/bin/sh

# script/test: Run test suite for application.

#set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

./script/clean
./script/build

 go test -race  -coverpkg=./... -coverprofile=covprofile ./...