#!/bin/sh

# script/test: Run all but the integration tests

#set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

./script/clean
./script/build
export SKIP_INTEGRATION_SETUP=true
 go test -race -short -coverpkg=./... -coverprofile=covprofile ./...
