#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

echo "==> Running bootstrap…"

script/bootstrap

echo "==> Cleaning bin folder…"

./script/clean